### ISSUE TITLE
NavBarHidden is work ?

### ISSUE THREAD

**Issue by AllanChen** [Kureev/react-native-navbar#1]
The NavBar can set hidden ?? i can not work for me .. BTW where can you find this document?

**Comment by Kureev** [comment]
Hi @AllanChen , can you describe the case you want to achieve? At the moment I haven't any special API to hide the navbar on the component layer, but I've implemented this in the *Usage example*:
```javascript
renderScene: function(route, navigator) {
    var Component = route.component;
    var navBar = route.navigationBar;

    if (navBar) {
      navBar = React.addons.cloneWithProps(navBar, {
        navigator: navigator,
        route: route
      });
    }

    return (
      <View style={styles.navigator}>
        {navBar}
        <Component navigator={navigator} route={route} />
      </View>
    );
}
```
Simply put, if you push route with navigationBar key, you'll have it. Otherwise, it'll be hidden.

**Comment by Kureev** [comment]
Closed until feedback
