### ISSUE TITLE
Aboute Animation

### ISSUE THREAD

**Issue by wangzhe1995** [Kureev/react-native-navbar#13]
When I was through the Navigator push a New View, animations and native IOS not the same

**Comment by Kureev** [comment]
If you're talking about animations for switching views, you can take a [look here](http://facebook.github.io/react-native/docs/navigator.html#configurescene) to get an idea how to do it and [here](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorSceneConfigs.js#L295-L338) to get a list of options

**Comment by wangzhe1995** [comment]
I got it .
