### ISSUE TITLE
could add a title button? 

### ISSUE THREAD

**Issue by fakefish** [Kureev/react-native-navbar#14]
I want to add two button in the place of title.

**Comment by Kureev** [comment]
Okay, you're free to do it: use `customTitle` for that. If you want an example for using custom elements in navbar component, you can take a look [here](#https://github.com/Kureev/react-native-navbar/tree/master/examples/customElements).

**Comment by fakefish** [comment]
oh, understand~ it is every cool about your code!

**Comment by Kureev** [comment]
Thanks for the warm words! Let me know if you'll need any other help!

**Comment by fakefish** [comment]
I have a question
in this code 
```
var NavigatorNavigationBarStyles = require('NavigatorNavigationBarStyles');
var StaticContainer = require('StaticContainer.react');
var cssVar = require('cssVar');
```
where is this component?

**Comment by Kureev** [comment]
My component depends on react-native. So, those components are implemented in the react-native core.
