### ISSUE TITLE
passProps seem doesn't work

### ISSUE THREAD

**Issue by iostalk** [Kureev/react-native-navbar#15]
I call `this.props.navigator.push` to the next scene, and pass some props to the next scene, and caught an error, the passed prop is undefined in the next view,it seems passProps doesn't work,and code is below:

```jsx
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 */
'use strict';

var React = require('react-native');
var Product = require('./product');
var Adapt = require('./adapt');

var mdskip = require('./data/mock-mdskip');
var context = require('./data/mock-context');
var NavigationBar = require('react-native-navbar');

var Detail = require("./ui/detail");
var styles = require("./ui/style");
var {
  Navigator,
  NavigatorIOS,
  AppRegistry,
  View,
  Text,
  StyleSheet,
  TouchableHighlight,
  ScrollView
} = React;

var product = new Product();
product.set("context", context.ModuleDatas);
product.set("config", context.TDetail);
product.set("mdskip", Adapt.transform(mdskip));
product.set("deviceType", "phone");

var RootComponent = React.createClass({
  getInitialState: function(){
    return {};
  },
  componentDidMount: function() {
    var self = this;
  },
  renderScene: function(route, navigator) {
    var product = this.state.product;

    var Component = route.component;
    var navBar = route.navigationBar;

    if (navBar) {
      navBar = React.addons.cloneWithProps(navBar, {
        navigator: navigator,
        route: route
      });
    }

    return (
      <View style={styles.navigator}>
        {navBar}
        <Component navigator={navigator} route={route} product={product} />
      </View>
    );
  },
  render: function() {

    if(context){
      return (
        <Navigator
        style={styles.navigator}
        renderScene={this.renderScene}
        initialRoute={{
          component: Entrance,
          navigationBar: <NavigationBar
            title="Initial View"
            onNext={this.handleNext}
          />
        }}
      />
      );
    }else{
      return (
        <View></View>
      )
    }
  }
});

var Entrance = React.createClass({
  render: function(){
    return (
      <View style={styles.clickMe}>
        <TouchableHighlight onPress={this.onPress} underlayColor="#B5B5B5">
          <Text style={styles.clickMeText}>点我看详情</Text>
        </TouchableHighlight>
      </View>
    );
  },
  componentDidMount(){
    var self = this;
    product.onLoad(["context", "config", "mdskip"], function(context, config, mdskip){
      self.setState({
        "context": context,
        "config": config,
        "mdskip": mdskip
      });
    })
  },
  onPress: function(){
    var context = this.state.context;
    var config = this.state.config;
    var mdskip = this.state.mdskip;
    var product = this.props.product;

    this.props.navigator.push({
      title: context.title.itemTitle,
      component: DetailMain,
      backButtonTitle: 'Back',
      passProps: { config: config, mdskip: mdskip, product: product, context: context}
    });
  }
});

var DetailMain = React.createClass({
  getInitialState: function(){
    return {
      loading: false
    };
  },
  render: function(){
    return (
      <Detail config={this.props.config} mdskip={this.props.mdskip} product={this.props.product} context={this.props.context} navigator={this.props.navigator}/>
    )
  }
})

AppRegistry.registerComponent('DetailNative', () => RootComponent);

```

**Comment by Kureev** [comment]
So, in short, you need to pass parameters to your custom components in the navbar, right? It's not implemented yet, but I think I'll try to implement it right now, good catch!

**Comment by iostalk** [comment]
I don't want to pass parameters to my custom components in the navbar, but I want to pass to the next route.Just like the code in navigatorIOS example:
```
<NavigatorIOS
      initialRoute={{
        component: MyView,
        title: 'My View Title',
        passProps: { myProp: 'foo' },
      }}
    />
```

and 

```
this.props.navigator.push({
              title: NavigatorIOSExample.title,
              component: NavigatorIOSExample,
              backButtonTitle: 'Custom Back',
              passProps: {topExampleRoute: this.props.topExampleRoute || this.props.route},
            });
```

**Comment by Kureev** [comment]
`Navigator` is a more low-level thing than `NavigatorIOS`and it doesn't support that feature out-of-box, but it's not hard to implement. You just need to apply your custom parameters to the `NavigationBar` in the `renderScene`. Basically, it's all about re-render `NavigationBar` with changed props, so you can use `setProps` or just call `render`. I'll make an example for that.

**Comment by chirag04** [comment]
I had the same problem. Look at my last comment here: https://github.com/Kureev/react-native-navbar/issues/12

**Comment by Kureev** [comment]
So, have you solved this issue?

**Comment by iostalk** [comment]
No,the problem is blow，I use the navigator to go to next view, but in the next view, I found all the passed props in the next view is null!!!

![2015-04-22 10 09 35](https://cloud.githubusercontent.com/assets/659130/7266145/d4b7e3d4-e8d7-11e4-8459-cd3cae93f53a.png)
![2015-04-22 10 09 53](https://cloud.githubusercontent.com/assets/659130/7266144/d4adee4c-e8d7-11e4-9405-5cc031ad2b41.png)

**Comment by Kureev** [comment]
@iostalk Thanks for the screenshots, but the most important part is how you `renderScene`. Can you show me this part? Because all data you pass to `Navigator` will go to this function.

**Comment by iostalk** [comment]
My render scene:

```js
renderScene: function(route, navigator) {
    var Component = route.component;
    var navBar = route.navigationBar;
    var product = route.product;

    if (navBar) {
      navBar = React.addons.cloneWithProps(navBar, {
        navigator: navigator,
        route: route,
        product: product
      });
    }

    console.log(product);
    return (
      <View style={styles.navigator}>
        {navBar}
        <Component navigator={navigator} route={route} product={product} />
      </View>
    );
  },

  render: function() {
    return (
      <Navigator
        style={styles.navigator}
        renderScene={this.renderScene}
        initialRoute={{
          component: Entrance,
          navigationBar: <NavigationBar title="Hello~~~"/>,
          product: product
        }}
      />
    );
  }
```

**Comment by Kureev** [comment]
@iostalk ok, this code is totally fine, in your Entrance component you should get access to your product thru `this.props.product`. Is it `Entrance` component on the screenshots?

**Comment by iostalk** [comment]
![image](https://cloud.githubusercontent.com/assets/659130/7269729/f36a8a30-e908-11e4-89b5-609ea86e3587.png)
I could get the passProps in the router, I figure it out!

**Comment by Kureev** [comment]
@iostalk strange, I don't see you passing `passProps` in this code.

**Comment by Yidada** [comment]
我也遇到了同样的问题，使用navigator  的时候，好像它不跟NavigatorIOS一样会传递参数，我想问下您后来是怎么解决这个问题的呢？@iostalk

**Comment by Kureev** [comment]
那么，它（导航栏）改变了很多，因为在这里的最后一个注释。你使用哪种版本？你能为我们提供一个代码示例？@Yidada

P.S. Google translate FTW!

**Comment by Yidada** [comment]
You are so cool for translating my words.Do you mean my react-native version? It's 0.14. and my code seems like this:
 onPress:function () {
    var value = this.refs.main.refs.form.getValue();
    if (value) {
        this.props.navigator.push({
          id:'RegPhone2',
          passProps: {phonNum:value}
        })
      }
  },

**Comment by Kureev** [comment]
I'm not quite sure, but it could be that you have a problem with your refs. If that's not the case, then I'd like to know, where do you use your `passProps`? I can't find anything about it neither inside [official Navigator documentation](https://facebook.github.io/react-native/docs/navigator.html) nor in [my API specs](https://github.com/react-native-fellowship/react-native-navbar#api).

**Comment by Yidada** [comment]
You know, In China we don't have such a good react environment. many apis or functions need to be guess...hahaha ,sorry for my not rigorous. I'll read your API specs maybe I can found my solution.😊

**Comment by Yidada** [comment]
May be my question is just how to pass props when we use the Navigator to route my app?

**Comment by Kureev** [comment]
Well, I can explain it! When you use `<Navigator />`, you're able to specify a `renderScene` function which will decide how to render your scene. It accepts two arguments: `route` and `navigator`. In your particular case you're interested in a `route`. Every time you push a new route, you can pass any extra params to it and then use it to render your component. You can take a look on example I have [here](https://github.com/react-native-fellowship/react-native-navbar/blob/master/examples/Routing/index.ios.js). So, in this example I use Navigator's `initialRoute` property, which specifies the initial route in your application. It may contain any fields you want. In my case it's a `component` I render inside the scene. But at the same moment you can pass `foo: 'bar'` and use it thru the `route.foo` property to inject it into your component. 

Hope this helped!

**Comment by Yidada** [comment]
It's really helpful for me! I read your example and try it in my app .It works ! Thanks again!😊

**Comment by cspkop** [comment]
@Kureev - Thanks for the explanation! Your idea on passing 'route' as a property of a component in 'renderScene' method solved my problem too. Now I am able to access 'myInfo' value (which i passed using  'passProp' while pushing new scene) in my new scene like this: 'this.props.route.passProps.myInfo'

**Comment by zhouyuguo** [comment]
maybe this.props.navigator.currentRoute can solve ur problems.

**Comment by RonakKhandelwal** [comment]
Solved the Problem though if pass props worked it could have been better feature request?

**Comment by windhost** [comment]
I solve this problem by rendering scenes  this way 
 <Component {...route.passProps} navigator={navigator} route={route} />

**Comment by windhost** [comment]
I solve this problem by rendering scenes this way 
`<Component {...route.passProps} navigator={navigator} route={route} />`

**Comment by mafelix** [comment]
You can also pass the prop through this.props.navigator by creating a new property if it's within the same stack of I believe.

**Comment by wujunchuan** [comment]
@windhost it work for me!thanks~ 👍 👍

**Comment by Bing-Xia** [comment]
It seems like really an early topic from now, current RN version is 0.43, try below
`this.props.navigator.push({
                    component: ProfileUpdate, args: {type: 'birth'}
                })`
and get params in 'ProfileUpdate' page like:
`const type = this.props.type`

maybe can help some guys like me :)
