### ISSUE TITLE
Doesn't work with React-native 0.4

### ISSUE THREAD

**Issue by alinz** [Kureev/react-native-navbar#17]
Hello and thanks for the great component.

I've tried your component and it doesn't seem to work with new version. It does compile but I got blank screen.

Any help would be appreciated.

**Comment by Kureev** [comment]
Hi @alinz , 
Could you provide more information about the issue you have? Do you see this issue in examples or you're getting it on your own code? If so, could you please show me a component where you use it?

**Comment by mjw56** [comment]
This is the issue with this package not using 0.4.0. If you publish this package to npm you should be fine.

**Comment by Kureev** [comment]
@mjw56 It doesn't work at all on 0.4.0

**Comment by mjw56** [comment]
@Kureev really? I have an app using this with 0.4.0. also I updated my watchman and flow to latest, but not sure if that would do anything.

**Comment by Kureev** [comment]
@mjw56 Yep, looks weird: I have just a blank screen and no errors in the console. Check the gist: https://gist.github.com/Kureev/c3da5d676d2dc0e84795 it doesn't work in 0.4.0, mb you can find any mistake?

**Comment by mjw56** [comment]
Hmm, I am not using any custom elems in the navbar component. I'm on mobile so I can't test any code right now.

**Comment by Kureev** [comment]
I'm currently trying to investigate this bug, will keep you posted

**Comment by mjw56** [comment]
also I've noticed strange caching with Xcode. Close Xcode completely, rm -rf node_modules and npm install again. Then open Xcode again.

**Comment by Kureev** [comment]
You was right, publishing package.json with ^0.4 dep works fine, thanks!

**Comment by alinz** [comment]
Thanks!
