### ISSUE TITLE
Add `routeStack` prop to docs

### ISSUE THREAD

**Issue by voronianski** [Kureev/react-native-navbar#2]
I see `routeStack` prop in `getLeftButtonElement` method. So it's actually showing "Back" button even on initial route because never gets into https://github.com/Kureev/react-native-navbar/blob/master/index.js#L44

Should I keep the stack up to date manually?

**Comment by Kureev** [comment]
Nope. Yesterday I talked to @ericvicenti about arguments <Navigator/>'s `renderScene` takes. So, in the short future, when [this PR](https://github.com/facebook/react-native/pull/553) will be merged, you'll be able to track `routeStack` in the `renderScene`(third parameter will be `state` which contains `routeStack`).

**Comment by voronianski** [comment]
:+1:

**Comment by Kureev** [comment]
As far as FB guys changed their mind, now it's changed to use `navigator.getCurrentRoutes()`.
FYI @voronianski
