### ISSUE TITLE
borderBottom prop

### ISSUE THREAD

**Issue by hoodsy** [Kureev/react-native-navbar#29]
Would it be possible to provide a property to allow styling of the bottom border of the navbar?

In my case, I would like to "hide" the navbar from a particular view, while still leaving the customPrev button visible.

**Comment by JonasJonny** [comment]
You can style bottom border via style={}:
```
borderBottomColor: '#47315a',
borderBottomWidth: 1 / PixelRatio.get(),
```

---

About the Navigator transparency. I think it is not possible right now.

**Comment by hoodsy** [comment]
Ah ok. thanks

**Comment by Kureev** [comment]
I think you can just pass `borderBottomWidth: 0` in the case you want to hide it.

**Comment by hoodsy** [comment]
styling the navigator:
```<View style={{borderWidth: 100}}>
  {navBar}
  <Component navigator={navigator} route={route} />
</View>```
results in a border around the perimeter of the screen.

styling the navigationBar: 
```var navigationBar = (
  <NavigationBar
    title="Custom buttons"
    style={{borderBottomWidth: 0}}
    customPrev={<CustomPrevButton/>}
    customNext={<CustomNextButton/>}
  />
);```

seems to have no effect. 

Apologies if this is a silly question, I'm a relative beginner to react-native. For one of my views it would b very handy to hide the bottom border, as I can hide everything else! Thanks for your time with this :)

**Comment by Kureev** [comment]
I'll try to take a look on your example on this week. Thanks for reporting it, I'm always looking forward to improve my components :+1:

**Comment by JonasJonny** [comment]
@hoodsy You find a way how to "hide"/"make transparent" navigation component with back button visible and fixed to header? Can you provide gist or example? I am curious. Thanks

**Comment by hoodsy** [comment]
@JonasJonny unfortunately don't have a way to hide the bottom border. 

But in my case I plan to have a customPrev button, and hide the rest. Pretty much something like this: 
```customTitle={route.index == 3 ? null : <CustomTitle/>}```
and do this for navbar backgroundColor etc, while customPrev is active for all routes.

**Comment by Kureev** [comment]
@hoodsy I'll definitely look into it, but it seems only on weekend. If @JonasJonny can help you with this, I'll be very grateful for help.

**Comment by hoodsy** [comment]
not sure why this was giving trouble before.. seems to be easily addable (as you said @Kureev) with style={}...

**Comment by Rohit-R97** [comment]
The View which is wrapping the navigator may have caused the bottom border.
`<View style={{ borderWidth: 100 , borderBottomWidth: 0 }} >...`
This may be a solution.
