### ISSUE TITLE
Doesnt work with ListView

### ISSUE THREAD

**Issue by sthomp** [Kureev/react-native-navbar#33]
Trying to modify the basic example to use the 'AwesomeProject' component from the react native tutorial. Im mainly trying to see how the navbar works with a listview. 

```
    <Navigator
        style={styles.navigator}
        renderScene={this.renderScene}
        initialRoute={{
          component: AwesomeProject,
          navigationBar: <NavigationBar
            title="Initial View"
            onNext={this.handleNext}
          />
        }}
      />
```

However, when I scroll down it seems that the ListView gets 'stuck' and wont let me scroll down.

![navbar_listview](https://cloud.githubusercontent.com/assets/1254471/7556111/140593a2-f732-11e4-93ff-45a85902a84a.gif)

Maybe it will be helpful to include an example with a ListView?

Thanks.

**Comment by Kureev** [comment]
Can you confirm, that you haven't this issue without navbar?

**Comment by sthomp** [comment]
Yes I can confirm. If I change the render function to remove Navigator:

```
render() {
    return (
      <AwesomeProject></AwesomeProject>
    );
  }
```

I can scroll through the ListView normally.

**Comment by sthomp** [comment]
Hmm seems to have something to do with the style on the parent View not having flex. I can scroll if I change renderScene to this:

```
    return (
      <View style={[{flex: 1}, styles.navigator]}>
        {navBar}
        <Component navigator={navigator} route={route} />
      </View>
    );
```

**Comment by Kureev** [comment]
So it seems not a bug of component, more about scene composition

**Comment by sthomp** [comment]
Ok feel free to close this issue. Although just note that the examples won't work out-of-the-box with listview.
