### ISSUE TITLE
using peerDependencies over dependencies in package.json

### ISSUE THREAD

**Issue by alinz** [Kureev/react-native-navbar#38]
I think we should start using peerDependencies instead of dependencies for referring to `react-native`. 

I will provide PR in case you want to support this.

**Comment by Kureev** [comment]
You decided to move it to peerDependencies in all repos, right? :wink:

**Comment by alinz** [comment]
@Kureev I wanted to make cleaner :P I'm using it inside my app and I ended up doing a lot of dependencies changes. So I decided to go over all my dependencies and made them peer. :P

**Comment by Kureev** [comment]
hehe, anyway good work!
