### ISSUE TITLE
Document how this differs from Navigator.NavigationBar

### ISSUE THREAD

**Issue by amccloud** [Kureev/react-native-navbar#41]
I'm currently using Navigator.NavigationBar and i'm not sure why I would use react-native-navbar

**Comment by Kureev** [comment]
First of all, `react-native-navbar` has been introduced before facebook released their solution for it. There were only NavigatorIOS with non-customizable navbar and Navigator without navbar at all. But even with this feature from facebook you can provide your own node with custom navbar. This component can help you build it.
