### ISSUE TITLE
Call toggle from parent navigator

### ISSUE THREAD

**Issue by austin1030** [Kureev/react-native-navbar#43]
Hi

First of all thank you for creating this plugin.

One question, is there a way to call this.props.menuActions from parent component? I want to add an icon on top bar (right side) to open/close side menu.

Would you please help?

Thanks

Austin

**Comment by Kureev** [comment]
Hi Austin,
Thanks for the warm words :)

Are you sure you made an issue in the right project? :) It's navbar, not sidebar. Or I miss something?

Best,
Alexey

**Comment by austin1030** [comment]
I thought I made issue with right project but then when I look back, it was
other project. So sorry about that.

Also, looking at issue submitted on side-menu project, someone wrote
exactly what I was looking for.

So, can you please share a sample code where I can call menuActions.toggle?
or Sidemenu.toggle() from the parent panel?

Thank you so much.


*Austin Kim*
Senior IT System Analyst
Senior Software Application Developer
Senior Web Developer
Phone: (240) 424-5202

**Comment by Kureev** [comment]
@austin1030 https://github.com/Kureev/react-native-side-menu/blob/master/examples/simple/index.ios.js#L24
