### ISSUE TITLE
relax/remove PeerDependencies to make it work with 0.6-RC

### ISSUE THREAD

**Issue by chirag04** [Kureev/react-native-navbar#44]
Doesn't work with react-native 0.6. It's best to just have react-native as a dependency.

What do you think @Kureev

**Comment by Kureev** [comment]
I think you shouldn't use multiple version of react in your project. That's why we moved it from dependencies to peerDependencies.

**Comment by chirag04** [comment]
Agreed. Npm will smartly handle this case i think. 

https://github.com/chirag04/react-native-dashed-border/blob/master/package.json#L24-L26
Doesn't install react-native again inside react-native-dashed-border component.

**Comment by chirag04** [comment]
Or maybe just update peerDependencies version to support 0.6-RC?

**Comment by Kureev** [comment]
As I see it's about `>=0.4` so it should support `0.6`, but not sure about release candidate version.

**Comment by Kureev** [comment]
Fixed in `0.5.2`
