### ISSUE TITLE
lightContent setting doesn't work with ReactNative 0.6.0 anymore

### ISSUE THREAD

**Issue by aksonov** [Kureev/react-native-navbar#47]
It worked with 0.5.0, but not with 0.6.0
![ios simulator screen shot 30 2015 11 18 06](https://cloud.githubusercontent.com/assets/1321329/8427710/cc882bb0-1f19-11e5-9de7-b29d3345853c.png)

**Comment by JonasJonny** [comment]
React Native API changed.

@Kureev Please update https://github.com/Kureev/react-native-navbar/blob/master/index.js#L215-217 to ``StatusBarIOS.setStyle('light-content', false);`` and ``StatusBarIOS.setStyle('default', false);``

Thank you.
