### ISSUE TITLE
cssVar not exported in react-native 0.7

### ISSUE THREAD

**Issue by mattmo** [Kureev/react-native-navbar#48]
Details: https://github.com/facebook/react-native/issues/1821

As a result, cssVar references should be removed from this module:

https://github.com/Kureev/react-native-navbar/blob/master/index.js#L15

**Comment by Kureev** [comment]
Damn, I got issue about support 0.6.0 1 week ago. They're freaking fast.

**Comment by chirag04** [comment]
+1. Just got hit by this. @Kureev can we remove dependency on cssVar and put those colors in the code directly?

**Comment by Kureev** [comment]
Sure we can. Want to make a PR, @chirag04 / @mattmo ?

**Comment by chirag04** [comment]
I can PR. Will do it in some time.

**Comment by Kureev** [comment]
Perfect, looking forward for it

**Comment by chirag04** [comment]
#49

**Comment by Kureev** [comment]
`0.5.3` contain this fix.

**Comment by mattmo** [comment]
Great, thanks guys
