### ISSUE TITLE
Styling is broken with react-native@0.8.0-rc

### ISSUE THREAD

**Issue by dubert** [Kureev/react-native-navbar#53]
Attached is a screenshot of the CustomElements example.

<img width="487" alt="screen shot 2015-07-14 at 13 22 48" src="https://cloud.githubusercontent.com/assets/1843672/8679904/a45cb4f4-2a2b-11e5-8c8b-96b86e0268e1.png">

**Comment by Kureev** [comment]
Does it happens only in 0.8.0-rc?

**Comment by Kureev** [comment]
Try to update to `v0.6.1`, mb it'll help
