### ISSUE TITLE
componentWillUnmount and componentDidUnmount not working for renderScene components

### ISSUE THREAD

**Issue by hmm29** [Kureev/react-native-navbar#54]
Hi Kureev, I have a component for the renderScene called Settings

```javascript
this.props.navigate({
            component: Settings,
            navigationBar: <NavigationBar
                title="Settings"
                customPrev={<MenuIcon/>}
                customNext={<ProfileIcon/>}
                />  
});
```

Every time I try to use the componentDidMount and componentWillUnmount functions for the Settings component itself it doesn't work.

```javascript
var Settings = React.createClass({
   getInitialState() {
        return {
            phrase: "Hello"
        };
   },
    [...]
  componentDidMount() {
     console.log('Did Mount');
   },
  componentWillUnmount() {
     console.log('Will Unmount');
   },
  componentDidUnmount() {
    console.log('Did Unmount');
   },
    render() {
        return (
          <View style={styles.container}>
            <View style={styles.section}>
                <Text>{this.state.phrase}</Text>
            </View>
          </View>
        );
    }
});
```

as you can imagine, the componentDidUnmount and componentDidUnmount functions don't work for settings or any of the other components rendered with renderScene. 
Any insights?

I am using react-native v0.7.1 and react-native-navbar v0.6.0. Thanks

**Comment by Kureev** [comment]
No thoughts so far, but may I ask why you think it's related to `react-native-navbar`?

**Comment by hmm29** [comment]
When I use componentWillUnmount, for example, in components in a project without react-native-navbar, it works fine.

```js
'use strict';

var React = require('react-native');
var {
  Component,
  View,
  Text,
  PropTypes,
} = React;

var styles = require('./style');

module.exports = class ListItem extends Component {
  constructor() {
    this.propTypes = {
      message: PropTypes.object
    };
  }

  componentWillUnmount() {
    console.log('UNMOUNTED');
  }

  render() {
    var message = this.props.message;

    return (
      <View style={styles.container}>
        <Text>{message.authorName}</Text>
        <Text>{message.text}</Text>
      </View>
    );
  }
};
```

And I get 

[tid:com.facebook.React.JavaScript] "UNMOUNTED"

in the Xcode debugger just as expected whenever the component unmounts.

Also, none of the components rendered with the react-native-navbar renderScene have functioning componentWIllMount and componentDidMount callbacks. It's not just the Settings one I mentioned.

**Comment by Kureev** [comment]
But when you unmount the navbar so? In your examples I don't see anything that can afflict navbar unmounting

**Comment by hmm29** [comment]
sorry if i didn't make it clear

so, routing in react-native-navbar you do something like

```js
this.props.navigate({
            component: Settings,
            navigationBar: <NavigationBar
                title="Settings"
                customPrev={<MenuIcon/>}
                customNext={<ProfileIcon/>}
                />  
});
```
right?

Every time I try to reroute and change the component, the previously displayed component's unmounting callbacks do not fire.

So if I try to do,
```js
this.props.navigate({
            component: Settings,
            navigationBar: <NavigationBar
                title="Settings"
                customPrev={<MenuIcon/>}
                customNext={<ProfileIcon/>}
                />  
});
```
and then go to the next route,
```js
this.props.navigate({
            component: Profile,
            navigationBar: <NavigationBar
                title="Profile"
                customPrev={<MenuIcon/>}
                customNext={<AboutIcon/>}
                />  
});
```

The unmounting callbacks for Settings will not fire at all. The reason I think it has to do with react-native-navbar is that the unmounting callbacks DO work when 

1) the regular this.navigator.push({name: '', index: 1}) is used instead of 
this.navigator.push({component: Component, navbar: \<NavigationBar \>}), which is the route object react-native-navbar uses

2) and also when I don't use react-native navbar, it works fine. which is the case with this:

```js
module.exports = class ListItem extends Component {
  constructor() {
    this.propTypes = {
      message: PropTypes.object
    };
  }

  componentWillUnmount() {
    console.log('UNMOUNTED');
  }

  render() {
    var message = this.props.message;

    return (
      <View style={styles.container}>
        <Text>{message.authorName}</Text>
        <Text>{message.text}</Text>
      </View>
    );
  }
};
```
and 'UNMOUNTED' gets logged in the XCode debugger as it should.

So I'm not talking about the NavigationBar itself but the component that gets displayed under it in the route.

**Comment by hmm29** [comment]
I was a little confused and wondered if you had insights as to how to still make sure the unmounting functions work with react-native-navbar. I think it's a super awesome package and so I want to make sure that I can still use all of the component life cycle functions

**Comment by Kureev** [comment]
That's weird, I'll take a look asap

**Comment by hmm29** [comment]
Thanks, man

**Comment by hmm29** [comment]
I'll take a look too. None of the components displayed under the navbar have working unmounting functions

**Comment by Kureev** [comment]
Wow, that's sounds weird. The point is that I don't even know why that could happens - as you can see I don't do anything with `componentWillMount` etc functions. 
Maybe @brentvatne knows more about it?

**Comment by brentvatne** [comment]
@hmm29 - you could try adding a key to the NavigationBar components, it's possible that they are being reused

```
            navigationBar: <NavigationBar
                title="Profile"
                key="profile-nav-bar"
                customPrev={<MenuIcon/>}
                customNext={<AboutIcon/>}
                />  
```

**Comment by hmm29** [comment]
Thanks @brentvatne!!! I think that was it

**Comment by Kureev** [comment]
Thanks for help @brentvatne :+1:

**Comment by L3V147H4N** [comment]
This did not work for me

**Comment by L3V147H4N** [comment]
I'm using the navigator like this:

```javascript
<Navigator
  navigationBar={this.navigationBar()}
  configureScene={() => Navigator.SceneConfigs.FloatFromRight}
  initialRoute={{routeName : 'LoginView', stateName: 'LoginView', friendlyName : 'LogIn', index: 0}}
  renderScene={this.renderScene}
   />
```
