### ISSUE TITLE
Translucent Property.

### ISSUE THREAD

**Issue by piyushchauhan2011** [Kureev/react-native-navbar#58]
I want to make the navigation bar translucent. What do you recommend should be the best way to make the bar translucent. I know `<NavigatorIOS />` have a property of `translucent` which one can use but we have `<Navigator />` and I don't know about `translucent` property, seems like it doesn't have that property.

![screen shot 2015-07-23 at 2 45 29 pm](https://cloud.githubusercontent.com/assets/693487/8843232/80650b44-3149-11e5-9ffb-44f5381c7ab6.png)

**Comment by Kureev** [comment]
hm, I'm wondering if it's something different than opacity? You can just pass style prop and specify `opacity` key there

**Comment by Kureev** [comment]
For example now you're doing something like
```javascript
renderScene: function(route, navigator) {
  var Component = route.component;
  var navBar = route.navigationBar;

  if (navBar) {
    navBar = React.addons.cloneWithProps(navBar, {
      navigator: navigator,
      route: route
    });
  }

  return (
    <View style={styles.navigator}>
      {navBar}
      <Component navigator={navigator} route={route} />
    </View>
  );
}
```
but you can change return a little bit to make it looks like this:
```javascript
...
  return (
    <View style={styles.navigator}>
      <View style={{ opacity: 0.5, }}>
        {navBar}
      </View>
      <Component navigator={navigator} route={route} />
    </View>
  );
```

**Comment by Kureev** [comment]
@piyushchauhan2011 so, was it helpful or you're asking about something else?

**Comment by piyushchauhan2011** [comment]
It applies the opacity but I think translucent is different.

I tried with and without sidemenu. Translucent is when user can see the content during scrolling below the navbar like in screenshot of medium.

### Medium
![screen shot 2015-07-26 at 12 59 21 am](https://cloud.githubusercontent.com/assets/693487/8889946/c657ea42-3331-11e5-90df-29f6a046310f.png)

### Without Sidemenu
![screen shot 2015-07-26 at 12 56 06 am](https://cloud.githubusercontent.com/assets/693487/8889926/49d8daa8-3331-11e5-80cf-bd6e464bd5da.png)

### With Sidemenu
![screen shot 2015-07-26 at 12 56 43 am](https://cloud.githubusercontent.com/assets/693487/8889934/5310912e-3331-11e5-9dc9-e956e97ed47d.png)

**Comment by Kureev** [comment]
In your case you can fix it by adding `backgroundColor` property to `MainStyles.navigator`.

**Comment by piyushchauhan2011** [comment]
I tried it on `navigator`, it does solve the problem of side menu which was showing up earlier I couldn't get the `medium` like effect.

![screen shot 2015-07-26 at 10 11 41 am](https://cloud.githubusercontent.com/assets/693487/8891911/6fa6dfe8-337f-11e5-926f-9783e61f5b9a.png)

**Comment by Kureev** [comment]
You can implement it by using `backgroundStyle` from `0.7.2` version. The only point is that you can't use it in "casual" way described in examples. If you use navbar as `Navigator.navigationBar` property, it'll allocate special place for it. As I understood from your screenshots, you need to embed it into your `component` property. Maybe I'm wrong, but give it a shot and let me know.

@brentvatne Maybe you have any thoughts?

**Comment by Kureev** [comment]
Closed until new feedback
