### ISSUE TITLE
Back Button on Initial Route

### ISSUE THREAD

**Issue by kocyigityunus** [Kureev/react-native-navbar#6]
there is a back button on initial route even if i send null to the customPrev. it's null on the chrome debugger on too but's there is a "back button".

![screen shot 2015-04-06 at 01 34 58](https://cloud.githubusercontent.com/assets/922418/6998991/803d4b0a-dbfd-11e4-91c2-92d2fa267a05.png)

**Comment by kocyigityunus** [comment]
maybe you can add a isInitial prop to the bar, so anyone who wants to hide back button, can hide back button.

**Comment by Kureev** [comment]
Thanks for your feedback! Added `hidePrev` in 0.3.0
