### ISSUE TITLE
Couldn't change the background of the navbar

### ISSUE THREAD

**Issue by alejomendoza** [Kureev/react-native-navbar#60]
Hi Alexey!! Awesome work on this, I was trying it out and it's great! one thing I couldn't do is set the navbar background to 'transparent'. backgroundColor="transparent"

**Comment by Kureev** [comment]
Hi Alejandro! I'm feel myself very sorry for not responding you for a 2 weeks. I was busy making https://github.com/Kureev/browserify-react-live . So, answering your question: since version `0.7.2` you can use `backgroundStyle` property to customize background layer. If you using prev. version it's also fine and backgroundColor should work. The only case it may not work - if you also specify `style` property and override backgroundColor there. For this case I made this patch in `0.7.2`. Please, let me know if it works fine for you

**Comment by robtg4** [comment]
Hey Kureev,
 So with backgroundStyle would you just do the following:

<Navigator
        renderScene={this.renderScene}
        initialRoute={{
          component: Main,
          backgroundStyle: 'transparent',
          navigationBar: (
            <NavigationBar
              customTitle={<CustomTitle/>}
              customPrev={<CustomPrev/>} />
          ),
        }} />

as i can't make it work this way.

**Comment by alejomendoza** [comment]
Hi Alexey!! I finally didn't go for your solution. I found a way of implementing what I wanted, what I'm missing is how to change the background color of the selected tab (similar to instagram functionality). If you want to check out my final result is here: https://github.com/skyhitz/skyhitz-react-native-ios/blob/master/app/components/tabviews/maintabbar.js
![tabbar](https://cloud.githubusercontent.com/assets/5351127/9283333/968427a6-4298-11e5-8be9-17833f470a20.png)

**Comment by Kureev** [comment]
Hey @robtg4! I think we're talking about `react-native-navbar` so far, so `backgroundStyle` property should be applied to it. Also, not sure I got your idea with this part:

```javascript
navigationBar: (
customTitle={}
customPrev={} />
),
```

I'd say you need to do something like this instead:

```javascript
navigationBar: (
  <Navbar backgroundStyle={{ backgroundColor: 'transparent', }} />
),
```

**Comment by Kureev** [comment]
@alejomendoza Hi again! Not sure I can find where you're using my component in the code. I think you're building a great application, but not sure I understand what kind of help I can do for you. Make sure you read readme first and using component as I pointed out in examples.

**Comment by Kureev** [comment]
@alejomendoza Have you figured out how to solve this issue?

**Comment by robtg4** [comment]
ok thatnks @Kureev !

**Comment by robtg4** [comment]
Hey @Kureev - sorry for the delayed response - I still seem to not be able to make the navbar transparent - here is my code so far:

![screen shot 2015-09-06 at 2 16 05 am](https://cloud.githubusercontent.com/assets/13613075/9702874/48d9bbe0-543d-11e5-881f-b6679fc468f8.png)

and here's wha that looks like:

![screen shot 2015-09-06 at 2 16 42 am](https://cloud.githubusercontent.com/assets/13613075/9702875/54b61dd2-543d-11e5-87ab-33cd627dd8e7.png)

**Comment by Kureev** [comment]
- Update your library version
- In the new version (0.8.2) you should use style instead of `backgroundColor`

Would it solve your problem?

**Comment by Kureev** [comment]
Closed due to lack of feedback (+ check 1.0.0 version, it has `tintColor` property for this purpose)

**Comment by aaronbwatkins** [comment]
Hi @Kureev - this is perhaps my favorite react component...certainly the one I use most often, so thank you so much.  I've also tried:

```
<Navbar backgroundStyle={{ backgroundColor: 'transparent', }} />
```
and I am getting a white background.  I'm using the latest version of react-native-navbar.  Would I also need to adjust something in the obj-c file to accomplish this?  thanks so much.

**Comment by Kureev** [comment]
Hi @aaronbwatkins ! I think you need to try a `tintColor="transparent"` property, that should work.

**Comment by aaronbwatkins** [comment]
Thanks @Kureev - I just tried ``` tintColor = "transparent" ``` as well.  Still gives me a white background.  I also tried adding a style property to the NavBar and putting tintColor in my ```Stylesheet.create``` function.  Also tried ``` <Navbar backgroundStyle={{ tintColor: 'transparent', }} /> ``` to no avail.  I know this is also pretty tedious to do in Xcode/Swift.  No worries if it's not possible, I can manage with a white navBar for now.  Thanks again!

**Comment by Kureev** [comment]
I'll take a look on it asap, I promise.

**Comment by aaronbwatkins** [comment]
thanks a lot @Kureev . I appreciate that. :-)

**Comment by kkgelu** [comment]
```
                tintColor='transparent'
```
this actually worked for me..

**Comment by Kureev** [comment]
`backgroundColor` has nothing with a way you position elements. It's not necessary to put a navbar element at the end of your view and align it via `position: absolute`.

**Comment by kkgelu** [comment]
@Kureev you are absolutely right. I was saying that's only way I accomplished transparent nav bar  -- usually it flows over a picture inside a scrollview. I am hoping you or others can find a better approach.

**Comment by Kureev** [comment]
Hm, what stops you from something like this:
```jsx
<View style={container}>
  <Navbar {...navbarSettings} />
  <ScrollView {..scrollViewSettings} />
</View>
```
That shouldn't overlap a `ScrollView`, right?

**Comment by kkgelu** [comment]
@Kureev I might be totally misunderstanding what the issue was, I thought people want something like this:

<img width="374" alt="screen shot 2016-02-29 at 23 53 42" src="https://cloud.githubusercontent.com/assets/11604017/13411902/0aac66ea-df40-11e5-992e-97a4ff4e690e.png">

Anyway, the background of the navbar is transparent.

**Comment by Kureev** [comment]
Oh, I got what you mean, @kkgelu!

Well, in this particular use-case I'd recommend you to use the approach you suggested with 
```js
{
  position: 'absolute',
  top: 0,
}
```

**Comment by Nomieee** [comment]
Hi,
i want "transparent" header In REACT-NATIVE How?
I have header with white screen but i have already background image
