### ISSUE TITLE
Update read me example: "cloneWithProps is deprecated"

### ISSUE THREAD

**Issue by jadsonlourenco** [Kureev/react-native-navbar#61]
https://facebook.github.io/react/docs/clone-with-props.html

Can be:
```
if (navBar) {  
  // Replace it
  //navBar = React.addons.cloneWithProps(navBar, { navigator, route, });

  // New way
  navBar = React.cloneElement(navBar, { navigator, route, });
}
```

Is just a detail that help us on begin (copy/paste/test :grin:). 
Any way thanks for this component.

**Comment by Kureev** [comment]
Thanks for notice that! Mb you want to compose a pull request?

**Comment by jadsonlourenco** [comment]
Hi @Kureev I don't know your "rules" to pull, and this issue is easy to change only on read me for now, then I can change on "examples" files, etc.

But you can add on read example how I can push new route? ```onPrev={() => this.navigator.pop();}```  but not work.

**Comment by Kureev** [comment]
New syntax (i.e. `navBar = React.cloneElement(navBar, { navigator, route, });`) for RN 0.8.0+?

**Comment by jadsonlourenco** [comment]
Yes, I'm using RN 0.8.0, but I don't know if this new syntax start by this version, but is good to be updated with current version of RN, if not broken the old.

**Comment by Kureev** [comment]
It seems there are a lot of improvements since 0.8, probably I'll create an explicit branch for that and merge it into master when 0.9 would be released.

**Comment by jadsonlourenco** [comment]
Yes, I think the same, so do that, I fork now, and I will send a pull on night.

**Comment by chirag04** [comment]
@Kureev  0.9 RC is already out for long. Should we update anything here?

**Comment by Kureev** [comment]
I wasn't expect they to be so fast. Yeah, we definitely need to align the code with current stable release

**Comment by Kureev** [comment]
Done.
