### ISSUE TITLE
How do I create a normal push animation where the nav bar does not move?

### ISSUE THREAD

**Issue by InnovatingBliss** [Kureev/react-native-navbar#62]
Here's a video with how my code runs right now. The first 14 seconds are without passing a navigation bar to the new route. The second half is with a new nav bar.
[![screen_recording_-_youtube](https://cloud.githubusercontent.com/assets/2507486/9000639/88d98ff0-3718-11e5-993f-49a846eaac93.png)](https://youtu.be/oo7xx0qh7jA)

Code for reference: 

    class PeopleTab extends Component {
	render () {
		return (
			<Navigator
				ref='navigator'
				style={styles.container}
				initialRoute={{
					name: "people",
					component: PeopleList,
					navigationBar: (<NavigationBar hidePrev={true} title="home" shouldUpdate={false} />),
				}}
				renderScene={this.renderScene.bind(this)}
				/>
		);
	}

	renderScene(route, nav) {

		var Component = route.component;
		var navBar = route.navigationBar;

		if (navBar) {
			navBar = React.addons.cloneWithProps(navBar, {
				navigator: navigator,
				route: route
			});

		}
		console.log(route);

		switch (route.name) {
			case 'people':
				return (
					<View style={{ flex: 1, }}>
						{navBar}
						<Component navigator={nav} route={route} onNext={this.onNext.bind(this)} />
					</View>
				);
			case 'person':
				return (
					<View style={{ flex: 1, }}>
						{navBar}
						<Component navigator={nav} route={route} person={route.person} />
					</View>
				);
			default:
				return (<View/>);
		}
	}

	onNext(person) {
		this.refs.navigator.push({
			name: "person",
			component: PersonDetail,
			person: person,
			navigationBar: (<NavigationBar title="People" />), // Only in 2nd half of video
		});
	}
}

How can I get the navigator with your nav bar to do a push with the nav bar not moving?

**Comment by InnovatingBliss** [comment]
To clarify, I'm asking how to make a push navigation with a static nav bar ( only the buttons and title changing, not position ).

**Comment by dubert** [comment]
:+1:

I believe this is what he means:
![titlebaranimation](https://cloud.githubusercontent.com/assets/1843672/9014877/1e3bd628-3793-11e5-879e-2b6587415904.gif)

And I would love do be able to do it too!

**Comment by dubert** [comment]
I think a part of it is putting the NavBar in the navigator instead of the route. I'm still testing...

**Comment by InnovatingBliss** [comment]
Thanks @dubert for the cleaner gif. That's what I'm looking to accomplish.

**Comment by Kureev** [comment]
I think it's more related to side menu, than to header. What kind of support from the component level you want? In theory, you should be able to implement it already.

**Comment by Kureev** [comment]
Closed until new feedback

**Comment by resendefreitas** [comment]
@dubert "I think a part of it is putting the NavBar in the navigator instead of the route. I'm still testing..."
I'm trying to accomplish this too, any progress? I need my NavBar to be "global" in the app.

**Comment by dubert** [comment]
@resendefreitas the best you can do for now is putting the NavBar in the navigator, not the route. This will make it global. We can't do the animations for now. :(

**Comment by resendefreitas** [comment]
@dubert i was able to do it with the animation, but i wanted it with no animation. I did it by making one navbar for each one of the components and passaing the route props on. But it was crappy, well i'll make it global as you said. Thanks for the help
