### ISSUE TITLE
Can't build the examples

### ISSUE THREAD

**Issue by eyaleizenberg** [Kureev/react-native-navbar#63]
When I try to build the basic example I get this:

![screen shot 2015-08-25 at 09 02 02](https://cloud.githubusercontent.com/assets/1061345/9459807/49ee4c96-4b08-11e5-9590-342e78a76f86.png)

And when I try to build the custom elements I get this:

![screen shot 2015-08-25 at 09 02 21](https://cloud.githubusercontent.com/assets/1061345/9459813/5bbcdb9a-4b08-11e5-8629-d8ab5df92282.png)

**Comment by Kureev** [comment]
Which version of react-native are you using?

**Comment by eyaleizenberg** [comment]
RN 0.9

I got your package working on my project, however the title for some reason is not aligned with the buttons:

![screen shot 2015-08-25 at 10 01 14](https://cloud.githubusercontent.com/assets/1061345/9460594/564d5f38-4b10-11e5-8e32-ee5d7228a002.png)

**Comment by Kureev** [comment]
hm, I'll check it asap. Strange, haven't change it since first releases

**Comment by eyaleizenberg** [comment]
@Kureev I am less bothered by the example, the vertical centering is more important.

P.S - I also use your side-menu package. Great stuff! You rock! :wink:

**Comment by Kureev** [comment]
Both problems solved in `0.8.2`

**Comment by eyaleizenberg** [comment]
Awesome! Any ETA for 0.8.2? :wink:

**Comment by Kureev** [comment]
Already shipped :package:

**Comment by eyaleizenberg** [comment]
I'll check it out. (Your github page is still on 0.8)

**Comment by eyaleizenberg** [comment]
@Kureev The title is still not aligned correctly on 0.8.2

**Comment by Kureev** [comment]
@eyaleizenberg in this case you need to double-check your code, because if you open `Basic` example (I've updated it yesterday) it works fine.

**Comment by eyaleizenberg** [comment]
Hi @Kureev the examples on github have not been updated so I can't check it out...

**Comment by Kureev** [comment]
I'm so sorry, pushed :blush:
