### ISSUE TITLE
How to add react search bar to navbar?

### ISSUE THREAD

**Issue by robtg4** [Kureev/react-native-navbar#65]
Just wondering if this is a possibility and if so how would it be implemented with your build? Thanks again!

**Comment by Kureev** [comment]
Can you show me any example of desired functionality?

**Comment by robtg4** [comment]
Something like this:

![ba6b10b4dfae0484b1e387dc4140b138](https://cloud.githubusercontent.com/assets/13613075/9706488/c92d4b3c-54b4-11e5-8e9b-0f29a92f6cf9.gif)

I'm also working on the functionality in which the navbar disappears when I scroll down and only shows when I am at the top of the scrollview.

**Comment by Kureev** [comment]
Hi @robtg4!
I think the best way to implement this is to create `customNext` button with expected search behavior. Take a look on [example with custom elements](https://github.com/Kureev/react-native-navbar/tree/master/examples/customElements).

About scroll hide/show: if you want to scroll a navbar, you can just put it on the level of the content view. All in all it's just a component :wink:
