### ISSUE TITLE
On new route push the animation is slow when having a MapView

### ISSUE THREAD

**Issue by alfonsoperez** [Kureev/react-native-navbar#68]
Hi there,
Probably not strictly related to this, but I am pushing a new Screen with two MapViews, and the transition to that screen is not smooth at all, I am not sure in which other cases this may happen, anyone has faced the same issue?

Regards

**Comment by Kureev** [comment]
Hi! Personally I think it's not related to subj component, but trying to help you with your issue I recommend you to visit `reactiflux` channel on slack, thread `#react-native`.

And before I can close this issue, just to be sure: can you try remove component and do the same interaction again? Would you experience the same issue?

**Comment by alfonsoperez** [comment]
Hi Kureev, yep, when there are no MapView's the transition is completely smooth.

**Comment by Kureev** [comment]
So in this case I recommend you to ask this question at `reactiflux` channel. Unfortunately, I've never experienced this bug before and don't know how to solve it. 

Just a quick tip from my mind: maybe it's possible to use the same map without redrawing it? :wink:

**Comment by alfonsoperez** [comment]
Ok cool!, anyway I will look further into it myself.

**Comment by alfonsoperez** [comment]
Well, the problem was that the animations don't go smooth while there is some heavy task being performed such as rendering a MapView, what was I thinking posting this issue on here, anyway!.

The way to go around it seems to be to use [InteractionManager](https://facebook.github.io/react-native/docs/interactionmanager.html) API.
