### ISSUE TITLE
Having issues with accessing navigator object

### ISSUE THREAD

**Issue by brycemolder** [Kureev/react-native-navbar#69]
In this code, this.props.navigator.pop() is undefined.  Same with this.refs.nav.navigator.pop().  How do I access navigator object?  Thanks for your time.  Jeff

     <Navigator
        ref="nav"
        style={styles.navigator}
        renderScene={this.renderScene}
        initialRoute={{
          component: Search,
           navigationBar: <NavigationBar 
            titleColor="#ffffff"
            title="Global Search"
            backgroundStyle={{backgroundColor:'#424242'}}
            onPrev={() => this.props.navigator.pop()}
            prevTitle="Back"
            />
        }}
      />

**Comment by Kureev** [comment]
Hi Jeff! I recommend you to take a look on examples I made, especially on these lines: https://github.com/Kureev/react-native-navbar/blob/master/examples/basic/index.ios.js#L46-L62
