### ISSUE TITLE
Use Two Right Bar buttons

### ISSUE THREAD

**Issue by pmpSalween** [Kureev/react-native-navbar#70]
I manage to create two right bar buttons on Navbar. But I can't pass custom onNext functions. 
Here is what I tried. 

    'use strict';

    var React = require('react-native');

    var NavigationBar = require('react-native-navbar');

     var {
      StyleSheet,
      View,
      TouchableOpacity,
      Image,
    } = React;
    var {Router, Route, Actions, Animations, Schema} = require('react-native-router-flux');

    class CustomNav extends React.Component {
        onPrev(){
            if (this.props.onPrev){
                this.props.onPrev();
                return;
            }
            if (this.props.navigator && this.props.navigator.getCurrentRoutes().length > 1){
                Actions.pop();
            }
        }

        render() {
            return <NavigationBar style={styles.navBar}
                                  titleColor='white'
                                  buttonsColor='white'
                                  statusBar='lightContent'
                                  prevTitle={this.props.initial ? " " : null}
                                  onPrev={this.props.onPrev || Actions.pop}
                                  onNext={this.props.toggleSlideMenu || Actions.pop}
                                  customNext={< CustomNavButton toggleSlideMenu={this.props.toggleSlideMenu} refreshList={this.props.refreshList}/>}
            {...this.props}
            />
        }
    }

    class CustomNavButton extends React.Component {

      _toggleSlideMenu() {
        console.log('You Press _toggleSlideMenu' + this.props);
        this.props.toggleSlideMenu(); //undefined
      }

      _refreshButtonPress() {
        console.log('You Press _refreshButtonPress');
       this.props.refreshList(); //undefined
      }

      render() {
        return (
          <View style={styles.twoButtonView}>
            <TouchableOpacity onPress={this._refreshButtonPress}>
              <Image source={require('image!refresh-icon')} style={styles.refreshButton}/>
            </TouchableOpacity>

            <TouchableOpacity onPress={this._toggleSlideMenu}>
              <Image source={require('image!menu')} style={styles.menuButton}/>
            </TouchableOpacity>
          </View>
        );
      }
    }

    var styles = StyleSheet.create({
        navBar: {
            backgroundColor: '#000000'
        },
        menuButton: {
          top: 30,
          width:30,
          height: 25,
          right: 10,
          tintColor : 'white'
      },
      refreshButton: {
        top: 30,
        width:30,
        height: 25,
        right: 15,
        tintColor : 'white'
    },
      twoButtonView: {
        flexDirection: 'row',
      }
    });

**Comment by Kureev** [comment]
It just doesn't work like this: if you want to create a custom button / group of buttons, you should use `customNext` to display desired component at the right side. What about navigation access: you should propagate your navigator property to children buttons:
```javascript
const customNext = (
  <CustomButtonWrapper>
    <Button1 />
    <Button2 />
  </CustomButtonWrapper>
);
```
In `CustomButtonWrapper` component you should render your child views with {...props} and that should solve your issue.

**Comment by pmpSalween** [comment]
Perfect. Thanks!

**Comment by Albinzr** [comment]
This is great
