### ISSUE TITLE
Update to React 0.11.0

### ISSUE THREAD

**Issue by idibidiart** [Kureev/react-native-navbar#71]
I had various compilation errors when updating to React 0.11.0

I was able to fix all errors but the output on the simulator looked terrible, like something has gone really wrong, yet no error messages.

**Comment by Kureev** [comment]
Hard to say what goes wrong, and why you think it's related to this component. I've rewritten this component and released `1.0.0` version (supports RN 0.12.0+), so mb your issue has been solved already.
