### ISSUE TITLE
How do I trigger a function in the content component from the right button?

### ISSUE THREAD

**Issue by maggerbo** [Kureev/react-native-navbar#72]
Hi @Kureev 

Thanks for a great component.

I have a hard time figuring out how I trigger a function on the component from the navbar. For example from the right button. Let's say I have an edit button. When I press that button I want to change something on the component in the route. How is this done correctly, do you have an example or some input?

All help would be much appreciated. Thank you!

Kind regards,
Mathias

**Comment by morenoh149** [comment]
I agree. Conceptually I'd like to define functions on a component that are triggered by a buton press on the navbar. However, following the example in the readme. The callback to the next button is defined in the component passing in props to the navigator. Thinking about this myself now.

**Comment by Kureev** [comment]
I think that's more about preferred way to communicate between components. I don't want to push my opinion on it, but one of the possible solutions is to use something like redux

**Comment by jforaker** [comment]
I think i was able to achieve what you are asking about. In my case I need to fire a route change from the custom button.

First I set up a mapper switch statement from the top level Navigator component:

```
        return (

            <Navigator
                initialRoute={initprops}
                renderScene={this._renderScene}
                />
        );
```

Then embed the nav in the props of the CustomNext (for some reason i couldnt name it "navigator"):

```
        switch (route.component) {
            case Events:
                return (
                    <View style={flexd}>
                        <NavigationBar
                            backgroundStyle={{ backgroundColor: 'black' }}
                            customPrev={<CustomPrev/>}
                            customNext={<CustomNext nav={nav} />}/>  /**** <---there ***/
                        <Component navigator={nav}/>
                    </View>
                );
            default:
                return (
                    <View style={flexd}>
                        <Home navigator={nav}/>
                    </View>
                );
        }
```

And then

```
class CustomNext extends React.Component {

    goToView(id){
        this.props.nav.push({component:id});
    }

    render() {
        return (
            <TouchableOpacity onPress={() => this.goToView(Events) }>
                <View style={styles.headerX}>
                    <View style={styles.navTop}>
                        <View style={[styles.headerItem]}>
                            <Image
                                source={{ uri: nextImage }}
                                style={styles.rightButton}
                                />
                        </View>
                    </View>
                </View>
            </TouchableOpacity>
        );
    }
}
```

**Comment by Kureev** [comment]
I'd recommend you create a custom navigation bar for every new screen, but in general, seems you solved you problem :+1:
