### ISSUE TITLE
Remove iOS-specific code so this can be cross-platform with Android

### ISSUE THREAD

**Issue by timothytripp** [Kureev/react-native-navbar#78]
I've just started with React-Native so I missed the "iOS-only" phase but since Navigator is cross-platform this would be an excellent way to implement cross platform view, especially since the Navigator documentation is so sparse.  BUT this class uses StatusBarIOS which makes it non-Android compatible (maybe there are other things; I haven't had a chance to try yet).

**Comment by Kureev** [comment]
After a while, I came with a conclusion that this component should works for iOS platform only. Make this work on Android literally means to re-build whole UI part + introduce custom interactions. That looks like a different component for me.
