### ISSUE TITLE
Status bar and navbar => different background colors

### ISSUE THREAD

**Issue by Mokto** [Kureev/react-native-navbar#79]
Hi guys,

I do not think it is possible to do that. An exemple is better than words :

![capture d ecran 2015-10-06 a 19 43 29](https://cloud.githubusercontent.com/assets/5103928/10325785/90410b68-6c62-11e5-9e71-92e053610bef.png)

I want to have different background colors on status bar and navbar.

Is it possible ?

Thanks ! ;)

**Comment by Kureev** [comment]
Hi @Mokto!
Regarding to https://facebook.github.io/react-native/docs/statusbarios.html, we can't change background of the StatusBar, **but** as far as I know, StatusBar renders with **transparent** background what literally means that I can introduce one extra parameter for SideBar color. 

And yeah, you already can customize navbar background. Marking this as a feature request
