### ISSUE TITLE
Custom prev/next and onNext/onPrev callback

### ISSUE THREAD

**Issue by morenoh149** [Kureev/react-native-navbar#88]
If we use a custom button, do we lose triggering of the onNext/onPrev callback?

so then our custom button has to be a touchableHighlight and handle the interaction themselves? If so then that should also be noted in the docs.

**Comment by Kureev** [comment]
Yes, we do lose them.
Now I'm working on second version of this component, so I'd propose to wait until I finish it and apply your efforts to make better documentation for it.

**Comment by morenoh149** [comment]
okay
