### ISSUE TITLE
Any way react-native-navbar will work with react-native 0.11.4?

### ISSUE THREAD

**Issue by vinu123** [Kureev/react-native-navbar#92]
I upgraded react-native to 0.12.0 to use react-native-navbar but now I am running into a lot of other issues. So, I was just wondering if there's any way to make this component work with 0.11.4

**Comment by Kureev** [comment]
@vinu123 to be honest, I haven't tested it on 0.11.4, but I bet it will work with it without any problems. If can test it and confirm my thought, I would appreciate a PR to fix dependency version in package.json.

**Comment by vinu123** [comment]
@Kureev Just tried. No luck.
![peer-dependancies](https://cloud.githubusercontent.com/assets/240336/10578147/e63317e8-768d-11e5-97be-42441b45719f.png)

**Comment by Kureev** [comment]
@vinu123 you need to change `dependencies` hash in package.json first: `>=0.12` should be replaced by `>=0.11`

**Comment by vinu123** [comment]
@Kureev Works perfectly fine. Thanks so much.

**Comment by Kureev** [comment]
@vinu123 Awesome, can you compose a PR with this change?

**Comment by Kureev** [comment]
nvm, fixed in 1.0.3
