### ISSUE TITLE
Button element style error

### ISSUE THREAD

**Issue by 0bit** [Kureev/react-native-navbar#95]
I use v1.0.3.
when I use leftButton/RightButton with a react element, it raise a warning like this:
```
Warning: Failed propType: Invariant Violation: Invalid props.style key `fontSize` supplied to `View`.
Bad object: {
  "fontSize": 17,
  "letterSpacing": 0.5,
  "marginTop": 12
}
```
Then I found here:
```javascript
if (data._isReactElement) {
      return <View style={styles.navBarButton}>{data}</View>;
    }
```
https://github.com/Kureev/react-native-navbar/blob/b87324d86853d4f1ca1baccdb7b2583172001f05/index.js#L54

I'm not sure that the `style` in here whether just only need a `marginTop` is enough or not.

**Comment by TanTan-TT** [comment]
+1

**Comment by jackuhan** [comment]
use xxxStyle: Text.propTypes.style
