### ISSUE TITLE
breaking API changes starting from 1.0.x? 

### ISSUE THREAD

**Issue by aksonov** [Kureev/react-native-navbar#96]
Sorry, but it doesn't look OK! Now I have to change whole app to use latest version properly. Why don't mark old attributes as 'deprecated' and introduce new ones, like titleConfig and so on, but support old ones without breaking compatibility?

**Comment by Kureev** [comment]
@aksonov You can still use 0.x versions. Every major release breaks backward compatibility. Check http://semver.org/ for more details.
